OPENQASM 2.0;
include "qelib1.inc";
qreg target[1];
qreg controllers[2];
creg b[3];
x target[0];
x controllers[0];
h controllers[1];
t controllers[1];
cx controllers[0],controllers[1];
tdg controllers[1];
cx target[0],controllers[1];
t controllers[1];
cx controllers[0],controllers[1];
tdg controllers[1];
h controllers[1];
barrier target[0],controllers[0],controllers[1];
measure controllers[1] -> b[0];
measure controllers[0] -> b[1];
measure target[0] -> b[2];